#!/bin/sh

BASEDIR=$(dirname "$0")
cd $BASEDIR/..
pwd

function myreplace {
    file=$1
    if [[ ! -L "~/$1" && -f "$1" ]]; then
        if [[ -f "~/$1" ]]; then
            mv "~/$1" "~/$1.orig"
        fi
        ln -s "$1" "~/$1"
    fi
}

#if [[ ! -L "~/.bashrc" ]]; then
myreplace ".bashrc"
myreplace ".bash_aliases"
