#!/bin/bash

function myreplace {
    file=$1
    cd ~
    if [[ ! -L "$file" ]]; then
        cd ~
        if [[ -f "$1" ]]; then
            mv "$1" "$1.orig"
        fi
        echo "Set $1"
        ln -s "./dotfiles/$1" "$1"
    fi
}

#if [[ ! -L "~/.bashrc" ]]; then
myreplace ".bashrc"
myreplace ".bash_aliases"
